import plugin from 'tailwindcss/plugin';
import animate from 'tailwindcss-animate';

export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontSize: {
        'display-1': 'var(--text-display-1)',
        'display-2': 'var(--text-display-2)',
        'display-3': 'var(--text-display-3)',
        'title': 'var(--text-title)',
        'body-1': 'var(--text-body-1)',
        'body': 'var(--text-body)',
        'small': 'var(--text-small)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        sidebar: {
          DEFAULT: 'var(--sidebar-background)',
          foreground: 'var(--sidebar-foreground)',
          primary: 'var(--sidebar-primary)',
          'primary-foreground': 'var(--sidebar-primary-foreground)',
          accent: 'var(--sidebar-accent)',
          'accent-foreground': 'var(--sidebar-accent-foreground)',
          border: 'var(--sidebar-border)',
          ring: 'var(--sidebar-ring)',
        },
           // Brand - Blue
        'blue-50': 'var(--color-blue-50)',
        'blue-100': 'var(--color-blue-100)',
        'blue-200': 'var(--color-blue-200)',
        'blue-300': 'var(--color-blue-300)',
        'blue-400': 'var(--color-blue-400)',
        'blue-500': 'var(--color-blue-500)',
        'blue-600': 'var(--color-blue-600)',
        'blue-700': 'var(--color-blue-700)',
        'blue-800': 'var(--color-blue-800)',
        'blue-900': 'var(--color-blue-900)',
        'blue-950': 'var(--color-blue-950)',

        // Brand - Indigo
        'indigo-50': 'var(--color-indigo-50)',
        'indigo-100': 'var(--color-indigo-100)',
        'indigo-200': 'var(--color-indigo-200)',
        'indigo-300': 'var(--color-indigo-300)',
        'indigo-400': 'var(--color-indigo-400)',
        'indigo-500': 'var(--color-indigo-500)',
        'indigo-600': 'var(--color-indigo-600)',
        'indigo-700': 'var(--color-indigo-700)',
        'indigo-800': 'var(--color-indigo-800)',
        'indigo-900': 'var(--color-indigo-900)',
        'indigo-950': 'var(--color-indigo-950)',

        // Neutral - Sky
        'sky-50': 'var(--color-sky-50)',
        'sky-100': 'var(--color-sky-100)',
        'sky-200': 'var(--color-sky-200)',
        'sky-300': 'var(--color-sky-300)',
        'sky-400': 'var(--color-sky-400)',
        'sky-500': 'var(--color-sky-500)',
        'sky-600': 'var(--color-sky-600)',
        'sky-700': 'var(--color-sky-700)',
        'sky-800': 'var(--color-sky-800)',
        'sky-900': 'var(--color-sky-900)',
        'sky-950': 'var(--color-sky-950)',

        // States - Warning
        'warning-50': 'var(--color-warning-50)',
        'warning-100': 'var(--color-warning-100)',
        'warning-200': 'var(--color-warning-200)',
        'warning-300': 'var(--color-warning-300)',
        'warning-400': 'var(--color-warning-400)',
        'warning-500': 'var(--color-warning-500)',
        'warning-600': 'var(--color-warning-600)',
        'warning-700': 'var(--color-warning-700)',
        'warning-800': 'var(--color-warning-800)',
        'warning-900': 'var(--color-warning-900)',
        'warning-950': 'var(--color-warning-950)',

        // States - Infos (identique à blue)
        'infos-50': 'var(--color-infos-50)',
        'infos-100': 'var(--color-infos-100)',
        'infos-200': 'var(--color-infos-200)',
        'infos-300': 'var(--color-infos-300)',
        'infos-400': 'var(--color-infos-400)',
        'infos-500': 'var(--color-infos-500)',
        'infos-600': 'var(--color-infos-600)',
        'infos-700': 'var(--color-infos-700)',
        'infos-800': 'var(--color-infos-800)',
        'infos-900': 'var(--color-infos-900)',
        'infos-950': 'var(--color-infos-950)',

        // States - Success
        'success-50': 'var(--color-success-50)',
        'success-100': 'var(--color-success-100)',
        'success-200': 'var(--color-success-200)',
        'success-300': 'var(--color-success-300)',
        'success-400': 'var(--color-success-400)',
        'success-500': 'var(--color-success-500)',
        'success-600': 'var(--color-success-600)',
        'success-700': 'var(--color-success-700)',
        'success-800': 'var(--color-success-800)',
        'success-900': 'var(--color-success-900)',
        'success-950': 'var(--color-success-950)',

        // States - Error
        'error-50': 'var(--color-error-50)',
        'error-100': 'var(--color-error-100)',
        'error-200': 'var(--color-error-200)',
        'error-300': 'var(--color-error-300)',
        'error-400': 'var(--color-error-400)',
        'error-500': 'var(--color-error-500)',
        'error-600': 'var(--color-error-600)',
        'error-700': 'var(--color-error-700)',
        'error-800': 'var(--color-error-800)',
        'error-900': 'var(--color-error-900)',
        'error-950': 'var(--color-error-950)',
      },
    },
  },
  plugins: [animate, plugin],
};
