export const assessmentHistoryData = [
  {
    id: '1',
    assessmentId: '123', // assessment with id '123'
    assessmentName: 'Évaluation Qualité Client',
    evaluator: 'John Doe',
    date: '15 jan 2025',
    score: 34,
    status: 'Terminé',
    duration: '1h12 min',
  },
  {
    id: '2',
    assessmentId: '123',
    assessmentName: 'Évaluation Qualité Client',
    evaluator: 'Sophie Durand',
    date: '15 jan 2025',
    score: 84,
    status: 'Terminé',
    duration: '35 min',
  },
  {
    id: '3',
    assessmentId: '123',
    assessmentName: 'Évaluation Qualité Client',
    evaluator: 'Rachid El Fassi',
    date: '16 jan 2025',
    score: 78,
    status: 'Terminé',
    duration: '1h',
  },
  {
    id: '4',
    assessmentId: '123',
    assessmentName: 'Évaluation Qualité Client',
    evaluator: 'Fatima Zahra',
    date: '17 jan 2025',
    score: 91,
    status: 'Terminé',
    duration: '45 min',
  },
  {
    id: '4',
    assessmentId: '123',
    assessmentName: 'Évaluation Qualité Client',
    evaluator: 'Fatima Zahra',
    date: '17 jan 2025',
    score: 91,
    status: 'Terminé',
    duration: '45 min',
  },
  {
    id: '4',
    assessmentId: '123',
    assessmentName: 'Évaluation Qualité Client',
    evaluator: 'Fatima Zahra',
    date: '17 jan 2025',
    score: 91,
    status: 'Terminé',
    duration: '45 min',
  },
  {
    id: '4',
    assessmentId: '123',
    assessmentName: 'Évaluation Qualité Client',
    evaluator: 'Fatima Zahra',
    date: '17 jan 2025',
    score: 91,
    status: 'Terminé',
    duration: '45 min',
  },
  {
    id: '4',
    assessmentId: '123',
    assessmentName: 'Évaluation Qualité Client',
    evaluator: 'Fatima Zahra',
    date: '17 jan 2025',
    score: 91,
    status: 'Terminé',
    duration: '45 min',
  },
  {
    id: '3',
    assessmentId: '456', // another assessment with id '456'
    assessmentName: 'Audit de Sécurité',
    evaluator: 'Rachid El Fassi',
    date: '16 jan 2025',
    score: 78,
    status: 'Terminé',
    duration: '1h',
  },
  {
    id: '4',
    assessmentId: '456',
    assessmentName: 'Audit de Sécurité',
    evaluator: 'Fatima Zahra',
    date: '17 jan 2025',
    score: 91,
    status: 'Terminé',
    duration: '45 min',
  },
  {
    id: '5',
    assessmentId: '789',
    assessmentName: 'Bilan de Performance',
    evaluator: 'Omar Haddad',
    date: '18 jan 2025',
    score: 56,
    status: 'En cours',
    duration: '30 min',
  },
  {
    id: '6',
    assessmentId: '789',
    assessmentName: 'Bilan de Performance',
    evaluator: 'Leila Amrani',
    date: '19 jan 2025',
    score: 73,
    status: 'Terminé',
    duration: '50 min',
  },
];
