export const mockEvaluators = [
  {
    name: "Alice Dupont",
    email: "alice.dupont@example.com",
    assigned: 12,
    completed: 10,
    score: 87.5,
    lastActivity: "2025/05/20",
    statut: "actif",
  },
  {
    name: "Benoît Martin",
    email: "benoit.martin@example.com",
    assigned: 8,
    completed: 8,
    score: 92.0,
    lastActivity: "2025/05/19",
    statut: "inactif",
  },
  {
    name: "Clara Lefèvre",
    email: "clara.lefevre@example.com",
    assigned: 15,
    completed: 11,
    score: 79.3,
    lastActivity: "2025/05/18",
    statut: "en pause",
  },
  {
    name: "David Moreau",
    email: "david.moreau@example.com",
    assigned: 5,
    completed: 3,
    score: 65.0,
    lastActivity: "2025/05/15",
    statut: "inactif",
  },
  {
    name: "Élodie Bernard",
    email: "elodie.bernard@example.com",
    assigned: 20,
    completed: 18,
    score: 95.2,
    lastActivity: "2025/05/21",
    statut: "actif",
  },
  {
    name: "François Dubois",
    email: "francois.dubois@example.com",
    assigned: 7,
    completed: 6,
    score: 82.7,
    lastActivity: "2025/05/20",
    statut: "actif",
  },
  {
    name: "Gisèle Faure",
    email: "gisele.faure@example.com",
    assigned: 9,
    completed: 9,
    score: 88.1,
    lastActivity: "2025/05/16",
    statut: "en pause",
  },
  {
    name: "Hugo Pelletier",
    email: "hugo.pelletier@example.com",
    assigned: 4,
    completed: 4,
    score: 91.4,
    lastActivity: "2025/05/19",
    statut: "actif",
  },
  {
    name: "Isabelle Richard",
    email: "isabelle.richard@example.com",
    assigned: 13,
    completed: 12,
    score: 84.6,
    lastActivity: "2025/05/20 ",
    statut: "actif",
  },
  {
    name: "Julien Morel",
    email: "julien.morel@example.com",
    assigned: 6,
    completed: 4,
    score: 70.5,
    lastActivity: "2025/05/14",
    statut: "inactif",
  }
];