export const mockEvaluationsList = [
  {
    id: "eval-001",
    name: "Cloud Infrastructure",
    date: "15 jan 2025",
    score: 0,
    evolution: "0",
    status: "À revoir",
  },
  {
    id: "eval-002",
    name: "Cloud Infrastructure",
    date: "15 jan 2025",
    score: 0,
    evolution: "0",
    status: "À revoir",
  },
  {
    id: "eval-003",
    name: "Cloud Infrastructure",
    date: "15 jan 2025",
    score: 0,
    evolution: "0",
    status: "À revoir",
  },
  {
    id: "eval-004",
    name: "Cloud Infrastructure",
    date: "15 jan 2025",
    score: 0,
    evolution: "0",
    status: "En cours",
  },
  {
    id: "eval-005",
    name: "Cloud Infrastructure",
    date: "15 jan 2025",
    score: 0,
    evolution: "0",
    status: "En cours",
  },
  {
    id: "eval-006",
    name: "Cloud Infrastructure",
    date: "15 jan 2025",
    score: 84,
    evolution: "9",
    status: "Passé",
  },
  {
    id: "eval-007",
    name: "Cloud Infrastructure",
    date: "15 jan 2025",
    score: 34,
    evolution: "-2",
    status: "Passé",
  },
  {
    id: "eval-008",
    name: "Cloud Infrastructure",
    date: "15 jan 2025",
    score: 16,
    evolution: "-5",
    status: "Passé",
  },
  {
    id: "eval-009",
    name: "Cloud Infrastructure",
    date: "15 jan 2025",
    score: 84,
    evolution: "3",
    status: "Passé",
  },
  {
    id: "eval-010",
    name: "Cloud Infrastructure",
    date: "15 jan 2025",
    score: 84,
    evolution: "5",
    status: "Passé",
  },
];
