export const mockEvaluations = [
    {
      id: "1",
      name: "Maturité DevOps",
      evaluator: "John Doe",
      date: "18 jan 2025",
      score: 34,
      evolution: 14,
      status: "Terminé",
    },
    {
      id: "7822",
      name: "Performance Réseau",
      evaluator: "Doha Tahir",
      date: "15 jan 2025",
      score: 68,
      evolution: 18,
      status: "En attente",
    },
    {
      id: "3",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "15 jan 2025",
      score: 84,
      evolution: 19,
      status: "En retard",
    },
    {
      id: "4",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "15 jan 2025",
      score: 84,
      evolution: 20,
      status: "Terminé",
    },
    {
      id: "5",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "15 jan 2025",
      score: 84,
      evolution: 38,
      status: "Terminé",
    },
    {
      id: "6",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 fev 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "7",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "8",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "9",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "10",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "11",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "12",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "13",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "14",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "15",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "16",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "17",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "18",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "19",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "20",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "21",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "22",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "23",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "24",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
    {
      id: "26",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
     {
      id: "27",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
     {
      id: "28",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
     {
      id: "29",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
     {
      id: "30",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
     {
      id: "31",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
     {
      id: "32",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
     {
      id: "33",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },
     {
      id: "34",
      name: "Conformité RGPD",
      evaluator: "Samir Haji",
      date: "13 mar 2025",
      score: 13,
      evolution: 13,
      status: "Terminé",
    },


  ];
  